// English Premier League — mystery player pool for Pick Six.
// trophies: club + senior national team honours per project rules (approx.).
const EPL_PLAYER_DATA = [
  { name: "Erling Haaland", club: "Manchester City", country: "Norway", position: "FW", height: 75, trophies: 18, age: 25 },
  { name: "Mohamed Salah", club: "Liverpool", country: "Egypt", position: "FW", height: 70, trophies: 15, age: 33 },
  { name: "Kevin De Bruyne", club: "Manchester City", country: "Belgium", position: "MF", height: 71, trophies: 20, age: 34 },
  { name: "Virgil van Dijk", club: "Liverpool", country: "Netherlands", position: "DF", height: 75, trophies: 9, age: 34 },
  { name: "Rodri", club: "Manchester City", country: "Spain", position: "MF", height: 74, trophies: 16, age: 29 },
  { name: "Bukayo Saka", club: "Arsenal", country: "England", position: "FW", height: 70, trophies: 5, age: 24 },
  { name: "Phil Foden", club: "Manchester City", country: "England", position: "MF", height: 68, trophies: 16, age: 25 },
  { name: "Declan Rice", club: "Arsenal", country: "England", position: "MF", height: 73, trophies: 3, age: 26 },
  { name: "Bruno Fernandes", club: "Manchester United", country: "Portugal", position: "MF", height: 70, trophies: 5, age: 31 },
  { name: "Son Heung-min", club: "Tottenham", country: "South Korea", position: "FW", height: 71, trophies: 4, age: 33 },
  { name: "Richarlison", club: "Tottenham", country: "Brazil", position: "FW", height: 71, trophies: 3, age: 28 },
  { name: "Martin Ødegaard", club: "Arsenal", country: "Norway", position: "MF", height: 69, trophies: 3, age: 26 },
  { name: "Bernardo Silva", club: "Manchester City", country: "Portugal", position: "MF", height: 68, trophies: 16, age: 31 },
  { name: "Alisson", club: "Liverpool", country: "Brazil", position: "GK", height: 75, trophies: 10, age: 32 },
  { name: "William Saliba", club: "Arsenal", country: "France", position: "DF", height: 75, trophies: 3, age: 24 },
  { name: "Cole Palmer", club: "Chelsea", country: "England", position: "MF", height: 73, trophies: 2, age: 23 },
  { name: "Alexander Isak", club: "Newcastle", country: "Sweden", position: "FW", height: 75, trophies: 2, age: 26 },
  { name: "Gabriel Martinelli", club: "Arsenal", country: "Brazil", position: "FW", height: 70, trophies: 3, age: 24 },
  { name: "Ollie Watkins", club: "Aston Villa", country: "England", position: "FW", height: 72, trophies: 2, age: 29 },
  { name: "Pedro Neto", club: "Chelsea", country: "Portugal", position: "FW", height: 68, trophies: 8, age: 25 },
  { name: "Dominik Szoboszlai", club: "Liverpool", country: "Hungary", position: "MF", height: 73, trophies: 4, age: 24 },
  { name: "Enzo Fernández", club: "Chelsea", country: "Argentina", position: "MF", height: 69, trophies: 6, age: 24 },
  { name: "James Maddison", club: "Tottenham", country: "England", position: "MF", height: 68, trophies: 8, age: 28 },
  { name: "James Ward-Prowse", club: "West Ham", country: "England", position: "MF", height: 69, trophies: 6, age: 30 },
  { name: "Jarrod Bowen", club: "West Ham", country: "England", position: "FW", height: 70, trophies: 4, age: 28 },
  { name: "Lucas Paquetá", club: "West Ham", country: "Brazil", position: "MF", height: 71, trophies: 6, age: 28 },
  { name: "Jean-Philippe Mateta", club: "Crystal Palace", country: "France", position: "FW", height: 75, trophies: 3, age: 28 },
  { name: "Eberechi Eze", club: "Crystal Palace", country: "England", position: "MF", height: 70, trophies: 3, age: 27 },
  { name: "Marc Guéhi", club: "Crystal Palace", country: "England", position: "DF", height: 72, trophies: 3, age: 25 },
  { name: "Dean Henderson", club: "Crystal Palace", country: "England", position: "GK", height: 74, trophies: 4, age: 28 },
  { name: "João Palhinha", club: "Fulham", country: "Portugal", position: "MF", height: 72, trophies: 6, age: 30 },
  { name: "Antonee Robinson", club: "Fulham", country: "United States", position: "DF", height: 70, trophies: 3, age: 28 },
  { name: "Raúl Jiménez", club: "Fulham", country: "Mexico", position: "FW", height: 72, trophies: 8, age: 34 },
  { name: "Bernd Leno", club: "Fulham", country: "Germany", position: "GK", height: 74, trophies: 6, age: 33 },
  { name: "Anthony Gordon", club: "Newcastle", country: "England", position: "FW", height: 69, trophies: 4, age: 24 },
  { name: "Bruno Guimarães", club: "Newcastle", country: "Brazil", position: "MF", height: 70, trophies: 6, age: 27 },
  { name: "Sven Botman", club: "Newcastle", country: "Netherlands", position: "DF", height: 75, trophies: 4, age: 25 },
  { name: "Nick Pope", club: "Newcastle", country: "England", position: "GK", height: 77, trophies: 4, age: 33 },
  { name: "Morgan Gibbs-White", club: "Nottingham Forest", country: "England", position: "MF", height: 70, trophies: 4, age: 25 },
  { name: "Chris Wood", club: "Nottingham Forest", country: "New Zealand", position: "FW", height: 74, trophies: 6, age: 33 },
  { name: "Murillo", club: "Nottingham Forest", country: "Brazil", position: "DF", height: 72, trophies: 3, age: 22 },
  { name: "Anthony Elanga", club: "Nottingham Forest", country: "Sweden", position: "FW", height: 70, trophies: 4, age: 23 },
  { name: "Wilson Isidor", club: "Sunderland", country: "France", position: "FW", height: 72, trophies: 3, age: 24 },
  { name: "Dan Ballard", club: "Sunderland", country: "Northern Ireland", position: "DF", height: 74, trophies: 2, age: 26 },
  { name: "Simon Adingra", club: "Brighton", country: "Ivory Coast", position: "FW", height: 69, trophies: 4, age: 23 },
  { name: "Kaoru Mitoma", club: "Brighton", country: "Japan", position: "FW", height: 68, trophies: 4, age: 28 },
  { name: "Jan Paul van Hecke", club: "Brighton", country: "Netherlands", position: "DF", height: 74, trophies: 3, age: 24 },
  { name: "Bart Verbruggen", club: "Brighton", country: "Netherlands", position: "GK", height: 74, trophies: 3, age: 23 },
  { name: "Yoane Wissa", club: "Brentford", country: "DR Congo", position: "FW", height: 70, trophies: 4, age: 29 },
  { name: "Bryan Mbeumo", club: "Brentford", country: "Cameroon", position: "FW", height: 69, trophies: 4, age: 26 },
  { name: "Nathan Collins", club: "Brentford", country: "Ireland", position: "DF", height: 75, trophies: 3, age: 24 },
  { name: "Mark Flekken", club: "Brentford", country: "Netherlands", position: "GK", height: 76, trophies: 4, age: 32 },
  { name: "Antoine Semenyo", club: "Bournemouth", country: "Ghana", position: "FW", height: 71, trophies: 3, age: 25 },
  { name: "Justin Kluivert", club: "Bournemouth", country: "Netherlands", position: "FW", height: 69, trophies: 6, age: 26 },
  { name: "Marcos Senesi", club: "Bournemouth", country: "Argentina", position: "DF", height: 72, trophies: 4, age: 28 },
  { name: "David Brooks", club: "Bournemouth", country: "Wales", position: "MF", height: 68, trophies: 4, age: 28 },
  { name: "Morgan Rogers", club: "Aston Villa", country: "England", position: "FW", height: 73, trophies: 3, age: 22 },
  { name: "Emiliano Martínez", club: "Aston Villa", country: "Argentina", position: "GK", height: 75, trophies: 8, age: 33 },
  { name: "Ezri Konsa", club: "Aston Villa", country: "England", position: "DF", height: 72, trophies: 3, age: 28 },
  { name: "Gabriel Magalhães", club: "Arsenal", country: "Brazil", position: "DF", height: 73, trophies: 5, age: 27 },
  { name: "Kai Havertz", club: "Arsenal", country: "Germany", position: "FW", height: 74, trophies: 6, age: 26 },
  { name: "David Raya", club: "Arsenal", country: "Spain", position: "GK", height: 72, trophies: 6, age: 29 },
  { name: "Jurriën Timber", club: "Arsenal", country: "Netherlands", position: "DF", height: 70, trophies: 5, age: 23 },
  { name: "Leandro Trossard", club: "Arsenal", country: "Belgium", position: "FW", height: 67, trophies: 6, age: 30 },
  { name: "Lisandro Martínez", club: "Manchester United", country: "Argentina", position: "DF", height: 69, trophies: 8, age: 27 },
  { name: "Kobbie Mainoo", club: "Manchester United", country: "England", position: "MF", height: 71, trophies: 2, age: 20 },
  { name: "Alejandro Garnacho", club: "Manchester United", country: "Argentina", position: "FW", height: 68, trophies: 2, age: 21 },
  { name: "André Onana", club: "Manchester United", country: "Cameroon", position: "GK", height: 74, trophies: 8, age: 29 },
  { name: "Matheus Cunha", club: "Manchester United", country: "Brazil", position: "FW", height: 70, trophies: 4, age: 26 },
  { name: "João Gomes", club: "Wolves", country: "Brazil", position: "MF", height: 68, trophies: 4, age: 24 },
  { name: "Jørgen Strand Larsen", club: "Wolves", country: "Norway", position: "FW", height: 75, trophies: 3, age: 25 },
  { name: "Rayan Aït-Nouri", club: "Wolves", country: "Algeria", position: "DF", height: 70, trophies: 4, age: 23 },
  { name: "José Sá", club: "Wolves", country: "Portugal", position: "GK", height: 74, trophies: 6, age: 32 },
  { name: "Crysencio Summerville", club: "West Ham", country: "Netherlands", position: "FW", height: 68, trophies: 3, age: 23 },
  { name: "Luis Sinisterra", club: "Bournemouth", country: "Colombia", position: "FW", height: 68, trophies: 4, age: 26 },
  { name: "Dango Ouattara", club: "Bournemouth", country: "Burkina Faso", position: "FW", height: 71, trophies: 3, age: 23 },
  { name: "Igor Thiago", club: "Brentford", country: "Brazil", position: "FW", height: 73, trophies: 3, age: 23 },
  { name: "Kevin Schade", club: "Brentford", country: "Germany", position: "FW", height: 72, trophies: 3, age: 23 },
  { name: "Milos Kerkez", club: "Bournemouth", country: "Hungary", position: "DF", height: 69, trophies: 3, age: 22 },
  { name: "Joe Gomez", club: "Liverpool", country: "England", position: "DF", height: 72, trophies: 10, age: 28 },
  { name: "Curtis Jones", club: "Liverpool", country: "England", position: "MF", height: 71, trophies: 8, age: 24 },
  { name: "Alexis Mac Allister", club: "Liverpool", country: "Argentina", position: "MF", height: 69, trophies: 8, age: 26 },
  { name: "Ryan Gravenberch", club: "Liverpool", country: "Netherlands", position: "MF", height: 74, trophies: 6, age: 23 },
  { name: "Jeremy Doku", club: "Manchester City", country: "Belgium", position: "FW", height: 67, trophies: 16, age: 23 },
  { name: "Jack Grealish", club: "Manchester City", country: "England", position: "MF", height: 70, trophies: 16, age: 30 },
  { name: "Rúben Dias", club: "Manchester City", country: "Portugal", position: "DF", height: 74, trophies: 16, age: 28 },
  { name: "Ederson", club: "Manchester City", country: "Brazil", position: "GK", height: 74, trophies: 16, age: 31 },
  { name: "Nico O'Reilly", club: "Manchester City", country: "England", position: "MF", height: 74, trophies: 2, age: 20 },
  { name: "Trevoh Chalobah", club: "Chelsea", country: "England", position: "DF", height: 75, trophies: 4, age: 26 },
  { name: "Moisés Caicedo", club: "Chelsea", country: "Ecuador", position: "MF", height: 70, trophies: 4, age: 24 },
  { name: "Reece James", club: "Chelsea", country: "England", position: "DF", height: 70, trophies: 6, age: 26 },
  { name: "Robert Sánchez", club: "Chelsea", country: "Spain", position: "GK", height: 76, trophies: 4, age: 28 },
  { name: "Pedro Porro", club: "Tottenham", country: "Spain", position: "DF", height: 68, trophies: 4, age: 26 },
  { name: "Micky van de Ven", club: "Tottenham", country: "Netherlands", position: "DF", height: 75, trophies: 4, age: 24 },
  { name: "Guglielmo Vicario", club: "Tottenham", country: "Italy", position: "GK", height: 74, trophies: 4, age: 29 },
  { name: "João Pedro", club: "Chelsea", country: "Brazil", position: "FW", height: 72, trophies: 4, age: 24 },
  { name: "Estêvão", club: "Chelsea", country: "Brazil", position: "FW", height: 69, trophies: 2, age: 18 },
];
