// Global football — 150 players across top leagues worldwide.
// Coverage includes Premier League, La Liga, Serie A, Bundesliga, Ligue 1, Primeira Liga, Eredivisie,
// Scottish Premiership, Belgian Pro League, Swiss Super League, Greek Super League, Süper Lig,
// MLS, Liga MX, Brasileirão, Saudi Pro League, J1 League, K League 1, Argentine Primera, and more.
//
// trophies: count from English Wikipedia only — https://en.wikipedia.org/wiki/<Player_name>
//   Use the “Honours” section (team football only). Include club + senior national team honours.
//   Exclude the “Individual” / “Orders and special awards” style subsections.
//   Each season listed for a competition counts as one trophy (e.g. three seasons of La Liga = 3).
// Revisit pages periodically; Wikipedia is updated when players win new titles.
const FOOTBALL_PLAYER_DATA = [
  { name: "Erling Haaland", league: "Premier League", club: "Manchester City", country: "Norway", position: "FW", height: 75, trophies: 18 },
  { name: "Mohamed Salah", league: "Premier League", club: "Liverpool", country: "Egypt", position: "FW", height: 70, trophies: 15 },
  { name: "Kevin De Bruyne", league: "Premier League", club: "Manchester City", country: "Belgium", position: "MF", height: 71, trophies: 20 },
  { name: "Virgil van Dijk", league: "Premier League", club: "Liverpool", country: "Netherlands", position: "DF", height: 75, trophies: 9 },
  { name: "Rodri", league: "Premier League", club: "Manchester City", country: "Spain", position: "MF", height: 74, trophies: 16 },
  { name: "Bukayo Saka", league: "Premier League", club: "Arsenal", country: "England", position: "FW", height: 70, trophies: 5 },
  { name: "Phil Foden", league: "Premier League", club: "Manchester City", country: "England", position: "MF", height: 68, trophies: 16 },
  { name: "Declan Rice", league: "Premier League", club: "Arsenal", country: "England", position: "MF", height: 73, trophies: 3 },
  { name: "Bruno Fernandes", league: "Premier League", club: "Manchester United", country: "Portugal", position: "MF", height: 70, trophies: 5 },
  { name: "Son Heung-min", league: "Premier League", club: "Tottenham", country: "South Korea", position: "FW", height: 71, trophies: 4 },
  { name: "Richarlison", league: "Premier League", club: "Tottenham", country: "Brazil", position: "FW", height: 71, trophies: 3 },
  { name: "Martin Ødegaard", league: "Premier League", club: "Arsenal", country: "Norway", position: "MF", height: 69, trophies: 3 },
  { name: "Bernardo Silva", league: "Premier League", club: "Manchester City", country: "Portugal", position: "MF", height: 68, trophies: 16 },
  { name: "Alisson", league: "Premier League", club: "Liverpool", country: "Brazil", position: "GK", height: 75, trophies: 10 },
  { name: "William Saliba", league: "Premier League", club: "Arsenal", country: "France", position: "DF", height: 75, trophies: 3 },
  { name: "Cole Palmer", league: "Premier League", club: "Chelsea", country: "England", position: "MF", height: 73, trophies: 2 },
  { name: "Alexander Isak", league: "Premier League", club: "Newcastle", country: "Sweden", position: "FW", height: 75, trophies: 2 },
  { name: "Gabriel Martinelli", league: "Premier League", club: "Arsenal", country: "Brazil", position: "FW", height: 70, trophies: 3 },
  { name: "Ollie Watkins", league: "Premier League", club: "Aston Villa", country: "England", position: "FW", height: 72, trophies: 2 },
  { name: "Pedro Neto", league: "Premier League", club: "Chelsea", country: "Portugal", position: "FW", height: 68, trophies: 8 },
  { name: "Dominik Szoboszlai", league: "Premier League", club: "Liverpool", country: "Hungary", position: "MF", height: 73, trophies: 4 },
  { name: "Enzo Fernández", league: "Premier League", club: "Chelsea", country: "Argentina", position: "MF", height: 69, trophies: 6 },
  { name: "Kylian Mbappé", league: "La Liga", club: "Real Madrid", country: "France", position: "FW", height: 72, trophies: 18 },
  { name: "Vinícius Júnior", league: "La Liga", club: "Real Madrid", country: "Brazil", position: "FW", height: 69, trophies: 14 },
  { name: "Jude Bellingham", league: "La Liga", club: "Real Madrid", country: "England", position: "MF", height: 73, trophies: 8 },
  { name: "Lamine Yamal", league: "La Liga", club: "Barcelona", country: "Spain", position: "FW", height: 70, trophies: 3 },
  { name: "Robert Lewandowski", league: "La Liga", club: "Barcelona", country: "Poland", position: "FW", height: 72, trophies: 25 },
  { name: "Pedri", league: "La Liga", club: "Barcelona", country: "Spain", position: "MF", height: 66, trophies: 5 },
  { name: "Frenkie de Jong", league: "La Liga", club: "Barcelona", country: "Netherlands", position: "MF", height: 72, trophies: 5 },
  { name: "Antoine Griezmann", league: "La Liga", club: "Atlético Madrid", country: "France", position: "FW", height: 68, trophies: 10 },
  { name: "Jan Oblak", league: "La Liga", club: "Atlético Madrid", country: "Slovenia", position: "GK", height: 75, trophies: 9 },
  { name: "Marc-André ter Stegen", league: "La Liga", club: "Barcelona", country: "Germany", position: "GK", height: 72, trophies: 10 },
  { name: "Federico Valverde", league: "La Liga", club: "Real Madrid", country: "Uruguay", position: "MF", height: 72, trophies: 12 },
  { name: "Eduardo Camavinga", league: "La Liga", club: "Real Madrid", country: "France", position: "MF", height: 70, trophies: 10 },
  { name: "Aurélien Tchouaméni", league: "La Liga", club: "Real Madrid", country: "France", position: "MF", height: 72, trophies: 8 },
  { name: "Rodrygo", league: "La Liga", club: "Real Madrid", country: "Brazil", position: "FW", height: 68, trophies: 12 },
  { name: "Nico Williams", league: "La Liga", club: "Athletic Bilbao", country: "Spain", position: "FW", height: 72, trophies: 3 },
  { name: "Mikel Oyarzabal", league: "La Liga", club: "Real Sociedad", country: "Spain", position: "FW", height: 72, trophies: 3 },
  { name: "Takefusa Kubo", league: "La Liga", club: "Real Sociedad", country: "Japan", position: "FW", height: 66, trophies: 3 },
  { name: "Álex Baena", league: "La Liga", club: "Villarreal", country: "Spain", position: "MF", height: 68, trophies: 3 },
  { name: "Borja Iglesias", league: "La Liga", club: "Real Betis", country: "Spain", position: "FW", height: 73, trophies: 2 },
  { name: "Iago Aspas", league: "La Liga", club: "Celta Vigo", country: "Spain", position: "FW", height: 69, trophies: 3 },
  { name: "Gerard Moreno", league: "La Liga", club: "Villarreal", country: "Spain", position: "FW", height: 72, trophies: 3 },
  { name: "Dani Carvajal", league: "La Liga", club: "Real Madrid", country: "Spain", position: "DF", height: 70, trophies: 22 },
  { name: "David Alaba", league: "La Liga", club: "Real Madrid", country: "Austria", position: "DF", height: 71, trophies: 22 },
  { name: "Antonio Rüdiger", league: "La Liga", club: "Real Madrid", country: "Germany", position: "DF", height: 75, trophies: 8 },
  { name: "Victor Osimhen", league: "Serie A", club: "Napoli", country: "Nigeria", position: "FW", height: 72, trophies: 4 },
  { name: "Lautaro Martínez", league: "Serie A", club: "Inter", country: "Argentina", position: "FW", height: 68, trophies: 8 },
  { name: "Nicolò Barella", league: "Serie A", club: "Inter", country: "Italy", position: "MF", height: 67, trophies: 6 },
  { name: "Federico Dimarco", league: "Serie A", club: "Inter", country: "Italy", position: "DF", height: 70, trophies: 6 },
  { name: "Mike Maignan", league: "Serie A", club: "Milan", country: "France", position: "GK", height: 74, trophies: 4 },
  { name: "Rafael Leão", league: "Serie A", club: "Milan", country: "Portugal", position: "FW", height: 74, trophies: 4 },
  { name: "Theo Hernández", league: "Serie A", club: "Milan", country: "France", position: "DF", height: 72, trophies: 6 },
  { name: "Dušan Vlahović", league: "Serie A", club: "Juventus", country: "Serbia", position: "FW", height: 74, trophies: 6 },
  { name: "Federico Chiesa", league: "Serie A", club: "Juventus", country: "Italy", position: "FW", height: 70, trophies: 6 },
  { name: "Manuel Locatelli", league: "Serie A", club: "Juventus", country: "Italy", position: "MF", height: 72, trophies: 4 },
  { name: "Khvicha Kvaratskhelia", league: "Serie A", club: "Napoli", country: "Georgia", position: "FW", height: 69, trophies: 4 },
  { name: "Stanislav Lobotka", league: "Serie A", club: "Napoli", country: "Slovakia", position: "MF", height: 66, trophies: 4 },
  { name: "Lorenzo Pellegrini", league: "Serie A", club: "Roma", country: "Italy", position: "MF", height: 72, trophies: 3 },
  { name: "Paulo Dybala", league: "Serie A", club: "Roma", country: "Argentina", position: "FW", height: 68, trophies: 12 },
  { name: "Matteo Politano", league: "Serie A", club: "Napoli", country: "Italy", position: "FW", height: 66, trophies: 4 },
  { name: "Alessandro Bastoni", league: "Serie A", club: "Inter", country: "Italy", position: "DF", height: 75, trophies: 6 },
  { name: "Francesco Acerbi", league: "Serie A", club: "Inter", country: "Italy", position: "DF", height: 75, trophies: 4 },
  { name: "Gleison Bremer", league: "Serie A", club: "Juventus", country: "Brazil", position: "DF", height: 73, trophies: 4 },
  { name: "Teun Koopmeiners", league: "Serie A", club: "Atalanta", country: "Netherlands", position: "MF", height: 72, trophies: 2 },
  { name: "Ademola Lookman", league: "Serie A", club: "Atalanta", country: "Nigeria", position: "FW", height: 72, trophies: 2 },
  { name: "Harry Kane", league: "Bundesliga", club: "Bayern Munich", country: "England", position: "FW", height: 74, trophies: 12 },
  { name: "Jamal Musiala", league: "Bundesliga", club: "Bayern Munich", country: "Germany", position: "MF", height: 71, trophies: 8 },
  { name: "Joshua Kimmich", league: "Bundesliga", club: "Bayern Munich", country: "Germany", position: "MF", height: 68, trophies: 18 },
  { name: "Manuel Neuer", league: "Bundesliga", club: "Bayern Munich", country: "Germany", position: "GK", height: 74, trophies: 28 },
  { name: "Leroy Sané", league: "Bundesliga", club: "Bayern Munich", country: "Germany", position: "FW", height: 72, trophies: 12 },
  { name: "Florian Wirtz", league: "Bundesliga", club: "Bayer Leverkusen", country: "Germany", position: "MF", height: 71, trophies: 3 },
  { name: "Granit Xhaka", league: "Bundesliga", club: "Bayer Leverkusen", country: "Switzerland", position: "MF", height: 72, trophies: 3 },
  { name: "Julian Brandt", league: "Bundesliga", club: "Borussia Dortmund", country: "Germany", position: "MF", height: 72, trophies: 3 },
  { name: "Karim Adeyemi", league: "Bundesliga", club: "Borussia Dortmund", country: "Germany", position: "FW", height: 70, trophies: 2 },
  { name: "Emre Can", league: "Bundesliga", club: "Borussia Dortmund", country: "Germany", position: "MF", height: 72, trophies: 4 },
  { name: "Xavi Simons", league: "Bundesliga", club: "RB Leipzig", country: "Netherlands", position: "MF", height: 67, trophies: 4 },
  { name: "Loïs Openda", league: "Bundesliga", club: "RB Leipzig", country: "Belgium", position: "FW", height: 68, trophies: 3 },
  { name: "Christopher Nkunku", league: "Bundesliga", club: "RB Leipzig", country: "France", position: "MF", height: 68, trophies: 4 },
  { name: "Serhou Guirassy", league: "Bundesliga", club: "Borussia Dortmund", country: "Guinea", position: "FW", height: 72, trophies: 2 },
  { name: "Jonathan Tah", league: "Bundesliga", club: "Bayer Leverkusen", country: "Germany", position: "DF", height: 75, trophies: 3 },
  { name: "Edmond Tapsoba", league: "Bundesliga", club: "Bayer Leverkusen", country: "Burkina Faso", position: "DF", height: 75, trophies: 3 },
  { name: "Waldemar Anton", league: "Bundesliga", club: "Borussia Dortmund", country: "Germany", position: "DF", height: 72, trophies: 2 },
  { name: "Gregor Kobel", league: "Bundesliga", club: "Borussia Dortmund", country: "Switzerland", position: "GK", height: 74, trophies: 2 },
  { name: "Ousmane Dembélé", league: "Ligue 1", club: "Paris Saint-Germain", country: "France", position: "FW", height: 70, trophies: 12 },
  { name: "Achraf Hakimi", league: "Ligue 1", club: "Paris Saint-Germain", country: "Morocco", position: "DF", height: 70, trophies: 12 },
  { name: "Marquinhos", league: "Ligue 1", club: "Paris Saint-Germain", country: "Brazil", position: "DF", height: 72, trophies: 25 },
  { name: "Gianluigi Donnarumma", league: "Ligue 1", club: "Paris Saint-Germain", country: "Italy", position: "GK", height: 77, trophies: 6 },
  { name: "Vitinha", league: "Ligue 1", club: "Paris Saint-Germain", country: "Portugal", position: "MF", height: 66, trophies: 8 },
  { name: "Warren Zaïre-Emery", league: "Ligue 1", club: "Paris Saint-Germain", country: "France", position: "MF", height: 70, trophies: 4 },
  { name: "Jonathan David", league: "Ligue 1", club: "Lille", country: "Canada", position: "FW", height: 70, trophies: 3 },
  { name: "Pierre-Emerick Aubameyang", league: "Ligue 1", club: "Marseille", country: "Gabon", position: "FW", height: 72, trophies: 8 },
  { name: "Pau López", league: "Ligue 1", club: "Marseille", country: "Spain", position: "GK", height: 72, trophies: 3 },
  { name: "Elye Wahi", league: "Ligue 1", club: "Lens", country: "France", position: "FW", height: 70, trophies: 2 },
  { name: "Edon Zhegrova", league: "Ligue 1", club: "Lille", country: "Kosovo", position: "FW", height: 70, trophies: 3 },
  { name: "Téji Savanier", league: "Ligue 1", club: "Montpellier", country: "France", position: "MF", height: 68, trophies: 2 },
  { name: "Pierre Lees-Melou", league: "Ligue 1", club: "Nantes", country: "France", position: "MF", height: 72, trophies: 1 },
  { name: "Benjamin Bourigeaud", league: "Ligue 1", club: "Rennes", country: "France", position: "MF", height: 70, trophies: 3 },
  { name: "Lionel Messi", league: "MLS", club: "Inter Miami", country: "Argentina", position: "FW", height: 67, trophies: 45 },
  { name: "Luis Suárez", league: "MLS", club: "Inter Miami", country: "Uruguay", position: "FW", height: 71, trophies: 22 },
  { name: "Josef Martínez", league: "MLS", club: "Inter Miami", country: "Venezuela", position: "FW", height: 68, trophies: 8 },
  { name: "Héctor Herrera", league: "MLS", club: "Houston Dynamo", country: "Mexico", position: "MF", height: 69, trophies: 8 },
  { name: "Hany Mukhtar", league: "MLS", club: "Nashville SC", country: "Germany", position: "MF", height: 70, trophies: 2 },
  { name: "Cucho Hernández", league: "MLS", club: "Columbus Crew", country: "Colombia", position: "FW", height: 69, trophies: 3 },
  { name: "Luciano Acosta", league: "MLS", club: "FC Cincinnati", country: "Argentina", position: "MF", height: 64, trophies: 4 },
  { name: "Denis Bouanga", league: "MLS", club: "LAFC", country: "Gabon", position: "FW", height: 72, trophies: 3 },
  { name: "Giorgos Giakoumakis", league: "MLS", club: "Atlanta United", country: "Greece", position: "FW", height: 72, trophies: 3 },
  { name: "Riqui Puig", league: "MLS", club: "LA Galaxy", country: "Spain", position: "MF", height: 66, trophies: 6 },
  { name: "André-Pierre Gignac", league: "Liga MX", club: "Tigres UANL", country: "France", position: "FW", height: 69, trophies: 15 },
  { name: "Henry Martín", league: "Liga MX", club: "América", country: "Mexico", position: "FW", height: 70, trophies: 6 },
  { name: "Luis Romo", league: "Liga MX", club: "Monterrey", country: "Mexico", position: "MF", height: 72, trophies: 8 },
  { name: "Jesús Corona", league: "Liga MX", club: "Tijuana", country: "Mexico", position: "MF", height: 67, trophies: 8 },
  { name: "Alexis Vega", league: "Liga MX", club: "Toluca", country: "Mexico", position: "FW", height: 68, trophies: 6 },
  { name: "Óscar Jiménez", league: "Liga MX", club: "América", country: "Mexico", position: "GK", height: 72, trophies: 6 },
  { name: "Endrick", league: "Brasileirão", club: "Palmeiras", country: "Brazil", position: "FW", height: 67, trophies: 4 },
  { name: "Gabriel Barbosa", league: "Brasileirão", club: "Flamengo", country: "Brazil", position: "FW", height: 70, trophies: 8 },
  { name: "Pedro", league: "Brasileirão", club: "Flamengo", country: "Brazil", position: "FW", height: 72, trophies: 8 },
  { name: "Everton Ribeiro", league: "Brasileirão", club: "Flamengo", country: "Brazil", position: "MF", height: 66, trophies: 12 },
  { name: "Luiz Henrique", league: "Brasileirão", club: "Botafogo", country: "Brazil", position: "FW", height: 70, trophies: 3 },
  { name: "Hulk", league: "Brasileirão", club: "Atlético Mineiro", country: "Brazil", position: "FW", height: 69, trophies: 25 },
  { name: "Raphael Veiga", league: "Brasileirão", club: "Palmeiras", country: "Brazil", position: "MF", height: 70, trophies: 8 },
  { name: "Weverton", league: "Brasileirão", club: "Palmeiras", country: "Brazil", position: "GK", height: 74, trophies: 8 },
  { name: "Luuk de Jong", league: "Eredivisie", club: "PSV", country: "Netherlands", position: "FW", height: 75, trophies: 12 },
  { name: "Guus Til", league: "Eredivisie", club: "PSV", country: "Netherlands", position: "MF", height: 72, trophies: 4 },
  { name: "Orkun Kökcü", league: "Eredivisie", club: "Feyenoord", country: "Turkey", position: "MF", height: 69, trophies: 3 },
  { name: "Santiago Giménez", league: "Eredivisie", club: "Feyenoord", country: "Mexico", position: "FW", height: 72, trophies: 3 },
  { name: "Steven Bergwijn", league: "Eredivisie", club: "Ajax", country: "Netherlands", position: "FW", height: 70, trophies: 8 },
  { name: "Jerdy Schouten", league: "Eredivisie", club: "PSV", country: "Netherlands", position: "MF", height: 72, trophies: 4 },
  { name: "Cristiano Ronaldo", league: "Saudi Pro League", club: "Al Nassr", country: "Portugal", position: "FW", height: 74, trophies: 35 },
  { name: "Karim Benzema", league: "Saudi Pro League", club: "Al Ittihad", country: "France", position: "FW", height: 72, trophies: 28 },
  { name: "Neymar", league: "Saudi Pro League", club: "Al Hilal", country: "Brazil", position: "FW", height: 69, trophies: 30 },
  { name: "Rúben Neves", league: "Saudi Pro League", club: "Al Hilal", country: "Portugal", position: "MF", height: 71, trophies: 8 },
  { name: "Otávio", league: "Saudi Pro League", club: "Al Nassr", country: "Portugal", position: "MF", height: 68, trophies: 12 },
  { name: "Malcom", league: "Saudi Pro League", club: "Al Hilal", country: "Brazil", position: "FW", height: 69, trophies: 8 },
  { name: "Sergej Milinković-Savić", league: "Saudi Pro League", club: "Al Hilal", country: "Serbia", position: "MF", height: 75, trophies: 6 },
  { name: "Diogo Costa", league: "Primeira Liga", club: "Porto", country: "Portugal", position: "GK", height: 72, trophies: 6 },
  { name: "Rafa Silva", league: "Primeira Liga", club: "Benfica", country: "Portugal", position: "MF", height: 66, trophies: 12 },
  { name: "Kyogo Furuhashi", league: "Scottish Premiership", club: "Celtic", country: "Japan", position: "FW", height: 66, trophies: 8 },
  { name: "Matt O'Riley", league: "Scottish Premiership", club: "Celtic", country: "Denmark", position: "MF", height: 73, trophies: 4 },
  { name: "Kevin Denkey", league: "Belgian Pro League", club: "Club Brugge", country: "Togo", position: "FW", height: 72, trophies: 3 },
  { name: "Mauro Icardi", league: "Süper Lig", club: "Galatasaray", country: "Argentina", position: "FW", height: 68, trophies: 16 },
  { name: "Dries Mertens", league: "Süper Lig", club: "Galatasaray", country: "Belgium", position: "FW", height: 66, trophies: 8 },
  { name: "Anderson Lopes", league: "J1 League", club: "Yokohama F. Marinos", country: "Brazil", position: "FW", height: 69, trophies: 8 },
  { name: "Yuya Osako", league: "J1 League", club: "Vissel Kobe", country: "Japan", position: "FW", height: 66, trophies: 8 },
  { name: "Jesse Lingard", league: "K League 1", club: "FC Seoul", country: "England", position: "MF", height: 68, trophies: 6 },
  { name: "Joo Min-kyu", league: "K League 1", club: "Ulsan HD", country: "South Korea", position: "FW", height: 71, trophies: 4 },
  { name: "Edinson Cavani", league: "Argentine Primera", club: "Boca Juniors", country: "Uruguay", position: "FW", height: 73, trophies: 22 },
  { name: "Miguel Borja", league: "Argentine Primera", club: "River Plate", country: "Colombia", position: "FW", height: 69, trophies: 10 },
  { name: "Jean-Pierre Nsame", league: "Swiss Super League", club: "Young Boys", country: "Cameroon", position: "FW", height: 72, trophies: 12 },
  { name: "Fotis Ioannidis", league: "Greek Super League", club: "Panathinaikos", country: "Greece", position: "FW", height: 72, trophies: 3 }
];
