// The Ringer NBA Top 100 - 2025-26 season (nbarankings.theringer.com)
// Format: name, team, league (East/West), division, position, height (inches), rings
const NBA_PLAYER_DATA = [
  { name: "Nikola Jokic", team: "Nuggets", league: "West", division: "Northwest", position: "C", height: 83, rings: 2 },
  { name: "Shai Gilgeous-Alexander", team: "Thunder", league: "West", division: "Northwest", position: "PG", height: 78, rings: 0 },
  { name: "Giannis Antetokounmpo", team: "Bucks", league: "East", division: "Central", position: "PF", height: 83, rings: 1 },
  { name: "Luka Doncic", team: "Mavericks", league: "West", division: "Southwest", position: "PG", height: 79, rings: 0 },
  { name: "Victor Wembanyama", team: "Spurs", league: "West", division: "Southwest", position: "C", height: 88, rings: 0 },
  { name: "Anthony Edwards", team: "Timberwolves", league: "West", division: "Northwest", position: "SG", height: 76, rings: 0 },
  { name: "Stephen Curry", team: "Warriors", league: "West", division: "Pacific", position: "PG", height: 74, rings: 4 },
  { name: "Donovan Mitchell", team: "Cavaliers", league: "East", division: "Central", position: "SG", height: 73, rings: 0 },
  { name: "Cade Cunningham", team: "Pistons", league: "East", division: "Central", position: "PG", height: 79, rings: 0 },
  { name: "Kawhi Leonard", team: "Clippers", league: "West", division: "Pacific", position: "SF", height: 79, rings: 2 },
  { name: "Jayson Tatum", team: "Celtics", league: "East", division: "Atlantic", position: "SF", height: 80, rings: 1 },
  { name: "LeBron James", team: "Lakers", league: "West", division: "Pacific", position: "SF", height: 81, rings: 4 },
  { name: "Kevin Durant", team: "Suns", league: "West", division: "Pacific", position: "SF", height: 82, rings: 2 },
  { name: "Joel Embiid", team: "76ers", league: "East", division: "Atlantic", position: "C", height: 84, rings: 0 },
  { name: "Devin Booker", team: "Suns", league: "West", division: "Pacific", position: "SG", height: 78, rings: 0 },
  { name: "Jaylen Brown", team: "Celtics", league: "East", division: "Atlantic", position: "SG", height: 78, rings: 1 },
  { name: "Anthony Davis", team: "Lakers", league: "West", division: "Pacific", position: "C", height: 82, rings: 1 },
  { name: "Damian Lillard", team: "Bucks", league: "East", division: "Central", position: "PG", height: 74, rings: 0 },
  { name: "Tyrese Haliburton", team: "Pacers", league: "East", division: "Central", position: "PG", height: 77, rings: 0 },
  { name: "Karl-Anthony Towns", team: "Knicks", league: "East", division: "Atlantic", position: "C", height: 84, rings: 0 },
  { name: "Zion Williamson", team: "Pelicans", league: "West", division: "Southwest", position: "PF", height: 78, rings: 0 },
  { name: "Paolo Banchero", team: "Magic", league: "East", division: "Southeast", position: "PF", height: 82, rings: 0 },
  { name: "Chet Holmgren", team: "Thunder", league: "West", division: "Northwest", position: "C", height: 84, rings: 0 },
  { name: "Ja Morant", team: "Grizzlies", league: "West", division: "Southwest", position: "PG", height: 74, rings: 0 },
  { name: "Trae Young", team: "Hawks", league: "East", division: "Southeast", position: "PG", height: 73, rings: 0 },
  { name: "De'Aaron Fox", team: "Kings", league: "West", division: "Pacific", position: "PG", height: 75, rings: 0 },
  { name: "Jalen Brunson", team: "Knicks", league: "East", division: "Atlantic", position: "PG", height: 74, rings: 0 },
  { name: "Evan Mobley", team: "Cavaliers", league: "East", division: "Central", position: "C", height: 83, rings: 0 },
  { name: "Bam Adebayo", team: "Heat", league: "East", division: "Southeast", position: "C", height: 81, rings: 0 },
  { name: "Scottie Barnes", team: "Raptors", league: "East", division: "Atlantic", position: "SF", height: 80, rings: 0 },
  { name: "LaMelo Ball", team: "Hornets", league: "East", division: "Southeast", position: "PG", height: 78, rings: 0 },
  { name: "Franz Wagner", team: "Magic", league: "East", division: "Southeast", position: "SF", height: 82, rings: 0 },
  { name: "Jimmy Butler", team: "Heat", league: "East", division: "Southeast", position: "SF", height: 79, rings: 0 },
  { name: "Kyrie Irving", team: "Mavericks", league: "West", division: "Southwest", position: "PG", height: 74, rings: 1 },
  { name: "Mikal Bridges", team: "Knicks", league: "East", division: "Atlantic", position: "SF", height: 78, rings: 0 },
  { name: "Rudy Gobert", team: "Timberwolves", league: "West", division: "Northwest", position: "C", height: 85, rings: 0 },
  { name: "Jalen Williams", team: "Thunder", league: "West", division: "Northwest", position: "SF", height: 78, rings: 0 },
  { name: "Desmond Bane", team: "Grizzlies", league: "West", division: "Southwest", position: "SG", height: 77, rings: 0 },
  { name: "Brandon Ingram", team: "Pelicans", league: "West", division: "Southwest", position: "SF", height: 81, rings: 0 },
  { name: "Jamal Murray", team: "Nuggets", league: "West", division: "Northwest", position: "PG", height: 76, rings: 1 },
  { name: "Lauri Markkanen", team: "Jazz", league: "West", division: "Northwest", position: "PF", height: 84, rings: 0 },
  { name: "Tyrese Maxey", team: "76ers", league: "East", division: "Atlantic", position: "PG", height: 74, rings: 0 },
  { name: "Jaren Jackson Jr.", team: "Grizzlies", league: "West", division: "Southwest", position: "C", height: 83, rings: 0 },
  { name: "Darius Garland", team: "Cavaliers", league: "East", division: "Central", position: "PG", height: 73, rings: 0 },
  { name: "DeMar DeRozan", team: "Kings", league: "West", division: "Pacific", position: "SF", height: 78, rings: 0 },
  { name: "Alperen Sengun", team: "Rockets", league: "West", division: "Southwest", position: "C", height: 83, rings: 0 },
  { name: "Jrue Holiday", team: "Celtics", league: "East", division: "Atlantic", position: "PG", height: 76, rings: 1 },
  { name: "Kristaps Porzingis", team: "Celtics", league: "East", division: "Atlantic", position: "C", height: 85, rings: 1 },
  { name: "Derrick White", team: "Celtics", league: "East", division: "Atlantic", position: "SG", height: 76, rings: 1 },
  { name: "Domantas Sabonis", team: "Kings", league: "West", division: "Pacific", position: "C", height: 83, rings: 0 },
  { name: "Zach LaVine", team: "Bulls", league: "East", division: "Central", position: "SG", height: 77, rings: 0 },
  { name: "Anfernee Simons", team: "Trail Blazers", league: "West", division: "Northwest", position: "SG", height: 75, rings: 0 },
  { name: "CJ McCollum", team: "Pelicans", league: "West", division: "Southwest", position: "SG", height: 75, rings: 0 },
  { name: "Draymond Green", team: "Warriors", league: "West", division: "Pacific", position: "PF", height: 78, rings: 4 },
  { name: "Klay Thompson", team: "Mavericks", league: "West", division: "Southwest", position: "SG", height: 78, rings: 4 },
  { name: "Aaron Gordon", team: "Nuggets", league: "West", division: "Northwest", position: "PF", height: 81, rings: 1 },
  { name: "Austin Reaves", team: "Lakers", league: "West", division: "Pacific", position: "SG", height: 77, rings: 0 },
  { name: "Terry Rozier", team: "Heat", league: "East", division: "Southeast", position: "PG", height: 73, rings: 0 },
  { name: "Jerami Grant", team: "Trail Blazers", league: "West", division: "Northwest", position: "PF", height: 80, rings: 0 },
  { name: "Brook Lopez", team: "Bucks", league: "East", division: "Central", position: "C", height: 84, rings: 1 },
  { name: "Khris Middleton", team: "Bucks", league: "East", division: "Central", position: "SF", height: 80, rings: 1 },
  { name: "OG Anunoby", team: "Knicks", league: "East", division: "Atlantic", position: "SF", height: 79, rings: 0 },
  { name: "Jordan Poole", team: "Wizards", league: "East", division: "Southeast", position: "SG", height: 76, rings: 1 },
  { name: "Bobby Portis", team: "Bucks", league: "East", division: "Central", position: "PF", height: 83, rings: 1 },
  { name: "Jarrett Allen", team: "Cavaliers", league: "East", division: "Central", position: "C", height: 83, rings: 0 },
  { name: "Myles Turner", team: "Pacers", league: "East", division: "Central", position: "C", height: 84, rings: 0 },
  { name: "Pascal Siakam", team: "Pacers", league: "East", division: "Central", position: "PF", height: 81, rings: 1 },
  { name: "Marcus Smart", team: "Grizzlies", league: "West", division: "Southwest", position: "PG", height: 76, rings: 0 },
  { name: "Jabari Smith Jr.", team: "Rockets", league: "West", division: "Southwest", position: "PF", height: 83, rings: 0 },
  { name: "Jordan Clarkson", team: "Jazz", league: "West", division: "Northwest", position: "SG", height: 77, rings: 0 },
  { name: "Walker Kessler", team: "Jazz", league: "West", division: "Northwest", position: "C", height: 84, rings: 0 },
  { name: "Herbert Jones", team: "Pelicans", league: "West", division: "Southwest", position: "SF", height: 80, rings: 0 },
  { name: "Michael Porter Jr.", team: "Nuggets", league: "West", division: "Northwest", position: "SF", height: 82, rings: 1 },
  { name: "Kyle Kuzma", team: "Wizards", league: "East", division: "Southeast", position: "PF", height: 82, rings: 1 },
  { name: "Coby White", team: "Bulls", league: "East", division: "Central", position: "PG", height: 77, rings: 0 },
  { name: "Immanuel Quickley", team: "Raptors", league: "East", division: "Atlantic", position: "PG", height: 75, rings: 0 },
  { name: "Cole Anthony", team: "Magic", league: "East", division: "Southeast", position: "PG", height: 75, rings: 0 },
  { name: "RJ Barrett", team: "Raptors", league: "East", division: "Atlantic", position: "SF", height: 78, rings: 0 },
  { name: "Jaden McDaniels", team: "Timberwolves", league: "West", division: "Northwest", position: "SF", height: 81, rings: 0 },
  { name: "Scoot Henderson", team: "Trail Blazers", league: "West", division: "Northwest", position: "PG", height: 74, rings: 0 },
  { name: "Keegan Murray", team: "Kings", league: "West", division: "Pacific", position: "PF", height: 80, rings: 0 },
  { name: "Ausar Thompson", team: "Pistons", league: "East", division: "Central", position: "SG", height: 79, rings: 0 },
  { name: "Cameron Johnson", team: "Nets", league: "East", division: "Atlantic", position: "SF", height: 80, rings: 0 },
  { name: "Nikola Vucevic", team: "Bulls", league: "East", division: "Central", position: "C", height: 84, rings: 0 },
  { name: "Clint Capela", team: "Hawks", league: "East", division: "Southeast", position: "C", height: 82, rings: 0 },
  { name: "Jakob Poeltl", team: "Raptors", league: "East", division: "Atlantic", position: "C", height: 84, rings: 0 },
  { name: "Deandre Ayton", team: "Trail Blazers", league: "West", division: "Northwest", position: "C", height: 84, rings: 0 },
  { name: "Wendell Carter Jr.", team: "Magic", league: "East", division: "Southeast", position: "C", height: 82, rings: 0 },
  { name: "Jonas Valanciunas", team: "Wizards", league: "East", division: "Southeast", position: "C", height: 83, rings: 0 },
  { name: "Daniel Gafford", team: "Wizards", league: "East", division: "Southeast", position: "C", height: 82, rings: 0 },
  { name: "Ivica Zubac", team: "Clippers", league: "West", division: "Pacific", position: "C", height: 84, rings: 0 },
  { name: "Christian Wood", team: "Lakers", league: "West", division: "Pacific", position: "C", height: 82, rings: 0 },
  { name: "Robert Williams III", team: "Trail Blazers", league: "West", division: "Northwest", position: "C", height: 84, rings: 0 },
  { name: "Mitchell Robinson", team: "Knicks", league: "East", division: "Atlantic", position: "C", height: 84, rings: 0 },
  { name: "Markelle Fultz", team: "Magic", league: "East", division: "Southeast", position: "PG", height: 76, rings: 0 },
  { name: "Monte Morris", team: "Suns", league: "West", division: "Pacific", position: "PG", height: 75, rings: 0 },
  { name: "Malcolm Brogdon", team: "Trail Blazers", league: "West", division: "Northwest", position: "PG", height: 77, rings: 0 },
  { name: "Fred VanVleet", team: "Rockets", league: "West", division: "Southwest", position: "PG", height: 74, rings: 1 },
  { name: "Tyus Jones", team: "Suns", league: "West", division: "Pacific", position: "PG", height: 74, rings: 0 },
  { name: "D'Angelo Russell", team: "Lakers", league: "West", division: "Pacific", position: "PG", height: 76, rings: 0 },
  { name: "Russell Westbrook", team: "Nuggets", league: "West", division: "Northwest", position: "PG", height: 75, rings: 0 },
  { name: "Chris Paul", team: "Spurs", league: "West", division: "Southwest", position: "PG", height: 72, rings: 0 },
  { name: "Mike Conley", team: "Timberwolves", league: "West", division: "Northwest", position: "PG", height: 73, rings: 0 },
  { name: "Kyle Lowry", team: "76ers", league: "East", division: "Atlantic", position: "PG", height: 72, rings: 1 },
  { name: "Collin Sexton", team: "Jazz", league: "West", division: "Northwest", position: "PG", height: 73, rings: 0 },
  { name: "Gary Trent Jr.", team: "Raptors", league: "East", division: "Atlantic", position: "SG", height: 78, rings: 0 },
  { name: "Buddy Hield", team: "Warriors", league: "West", division: "Pacific", position: "SG", height: 76, rings: 0 },
  { name: "Malik Beasley", team: "Pistons", league: "East", division: "Central", position: "SG", height: 76, rings: 0 },
  { name: "Duncan Robinson", team: "Heat", league: "East", division: "Southeast", position: "SG", height: 79, rings: 0 },
  { name: "Norman Powell", team: "Clippers", league: "West", division: "Pacific", position: "SG", height: 76, rings: 1 },
  { name: "Bogdan Bogdanovic", team: "Hawks", league: "East", division: "Southeast", position: "SG", height: 78, rings: 0 },
  { name: "Kevin Huerter", team: "Kings", league: "West", division: "Pacific", position: "SG", height: 79, rings: 0 },
  { name: "Tim Hardaway Jr.", team: "Pistons", league: "East", division: "Central", position: "SG", height: 78, rings: 0 },
  { name: "Tyler Herro", team: "Heat", league: "East", division: "Southeast", position: "SG", height: 77, rings: 0 },
  { name: "Andrew Wiggins", team: "Warriors", league: "West", division: "Pacific", position: "SF", height: 79, rings: 1 },
  { name: "Harrison Barnes", team: "Kings", league: "West", division: "Pacific", position: "SF", height: 80, rings: 1 },
  { name: "Gordon Hayward", team: "Thunder", league: "West", division: "Northwest", position: "SF", height: 80, rings: 0 },
  { name: "Tobias Harris", team: "Pistons", league: "East", division: "Central", position: "PF", height: 80, rings: 0 },
  { name: "Julius Randle", team: "Knicks", league: "East", division: "Atlantic", position: "PF", height: 80, rings: 0 },
  { name: "John Collins", team: "Jazz", league: "West", division: "Northwest", position: "PF", height: 82, rings: 0 },
  { name: "Evan Fournier", team: "Knicks", league: "East", division: "Atlantic", position: "SG", height: 78, rings: 0 },
  { name: "Bojan Bogdanovic", team: "Nets", league: "East", division: "Atlantic", position: "SF", height: 80, rings: 0 },
  { name: "Luguentz Dort", team: "Thunder", league: "West", division: "Northwest", position: "SG", height: 76, rings: 0 },
  { name: "Alex Caruso", team: "Bulls", league: "East", division: "Central", position: "SG", height: 77, rings: 1 },
  { name: "Trey Murphy III", team: "Pelicans", league: "West", division: "Southwest", position: "SF", height: 80, rings: 0 },
];
