// NHL Top Players (approx) - Format matches NBA/NFL: name, team, league (East/West), division, position, height (inches), rings (Stanley Cups)
const NHL_PLAYER_DATA = [
  { name: "Connor McDavid", team: "Oilers", league: "West", division: "Pacific", position: "C", height: 73, rings: 0 },
  { name: "Nathan MacKinnon", team: "Avalanche", league: "West", division: "Central", position: "C", height: 72, rings: 1 },
  { name: "Auston Matthews", team: "Maple Leafs", league: "East", division: "Atlantic", position: "C", height: 75, rings: 0 },
  { name: "Leon Draisaitl", team: "Oilers", league: "West", division: "Pacific", position: "C", height: 74, rings: 0 },
  { name: "Cale Makar", team: "Avalanche", league: "West", division: "Central", position: "D", height: 72, rings: 1 },
  { name: "Nikita Kucherov", team: "Lightning", league: "East", division: "Atlantic", position: "RW", height: 71, rings: 2 },
  { name: "David Pastrnak", team: "Bruins", league: "East", division: "Atlantic", position: "RW", height: 72, rings: 0 },
  { name: "Artemi Panarin", team: "Rangers", league: "East", division: "Metropolitan", position: "LW", height: 71, rings: 0 },
  { name: "Sidney Crosby", team: "Penguins", league: "East", division: "Metropolitan", position: "C", height: 71, rings: 3 },
  { name: "Jack Eichel", team: "Golden Knights", league: "West", division: "Pacific", position: "C", height: 74, rings: 1 },
  { name: "Mikko Rantanen", team: "Avalanche", league: "West", division: "Central", position: "RW", height: 76, rings: 1 },
  { name: "Kirill Kaprizov", team: "Wild", league: "West", division: "Central", position: "LW", height: 71, rings: 0 },
  { name: "Matthew Tkachuk", team: "Panthers", league: "East", division: "Atlantic", position: "LW", height: 74, rings: 1 },
  { name: "Aleksander Barkov", team: "Panthers", league: "East", division: "Atlantic", position: "C", height: 75, rings: 1 },
  { name: "Igor Shesterkin", team: "Rangers", league: "East", division: "Metropolitan", position: "G", height: 73, rings: 0 },
  { name: "Roman Josi", team: "Predators", league: "West", division: "Central", position: "D", height: 73, rings: 0 },
  { name: "Quinn Hughes", team: "Canucks", league: "West", division: "Pacific", position: "D", height: 70, rings: 0 },
  { name: "Elias Pettersson", team: "Canucks", league: "West", division: "Pacific", position: "C", height: 74, rings: 0 },
  { name: "Mitch Marner", team: "Maple Leafs", league: "East", division: "Atlantic", position: "RW", height: 72, rings: 0 },
  { name: "William Nylander", team: "Maple Leafs", league: "East", division: "Atlantic", position: "RW", height: 72, rings: 0 },
  { name: "Brad Marchand", team: "Bruins", league: "East", division: "Atlantic", position: "LW", height: 69, rings: 1 },
  { name: "Patrice Bergeron", team: "Bruins", league: "East", division: "Atlantic", position: "C", height: 73, rings: 1 },
  { name: "Victor Hedman", team: "Lightning", league: "East", division: "Atlantic", position: "D", height: 78, rings: 2 },
  { name: "Andrei Vasilevskiy", team: "Lightning", league: "East", division: "Atlantic", position: "G", height: 75, rings: 2 },
  { name: "Steven Stamkos", team: "Lightning", league: "East", division: "Atlantic", position: "C", height: 73, rings: 2 },
  { name: "Brayden Point", team: "Lightning", league: "East", division: "Atlantic", position: "C", height: 72, rings: 2 },
  { name: "J.T. Miller", team: "Canucks", league: "West", division: "Pacific", position: "C", height: 73, rings: 0 },
  { name: "Jason Robertson", team: "Stars", league: "West", division: "Central", position: "LW", height: 75, rings: 0 },
  { name: "Roope Hintz", team: "Stars", league: "West", division: "Central", position: "C", height: 75, rings: 0 },
  { name: "Miro Heiskanen", team: "Stars", league: "West", division: "Central", position: "D", height: 73, rings: 0 },
  { name: "Jake Oettinger", team: "Stars", league: "West", division: "Central", position: "G", height: 78, rings: 0 },
  { name: "Joe Pavelski", team: "Stars", league: "West", division: "Central", position: "C", height: 73, rings: 0 },
  { name: "Connor Hellebuyck", team: "Jets", league: "West", division: "Central", position: "G", height: 76, rings: 0 },
  { name: "Mark Scheifele", team: "Jets", league: "West", division: "Central", position: "C", height: 75, rings: 0 },
  { name: "Kyle Connor", team: "Jets", league: "West", division: "Central", position: "LW", height: 73, rings: 0 },
  { name: "Josh Morrissey", team: "Jets", league: "West", division: "Central", position: "D", height: 75, rings: 0 },
  { name: "Tage Thompson", team: "Sabres", league: "East", division: "Atlantic", position: "C", height: 78, rings: 0 },
  { name: "Rasmus Dahlin", team: "Sabres", league: "East", division: "Atlantic", position: "D", height: 75, rings: 0 },
  { name: "Jack Hughes", team: "Devils", league: "East", division: "Metropolitan", position: "C", height: 71, rings: 0 },
  { name: "Jesper Bratt", team: "Devils", league: "East", division: "Metropolitan", position: "LW", height: 71, rings: 0 },
  { name: "Nico Hischier", team: "Devils", league: "East", division: "Metropolitan", position: "C", height: 73, rings: 0 },
  { name: "Dougie Hamilton", team: "Devils", league: "East", division: "Metropolitan", position: "D", height: 78, rings: 0 },
  { name: "Timo Meier", team: "Devils", league: "East", division: "Metropolitan", position: "RW", height: 73, rings: 0 },
  { name: "Erik Karlsson", team: "Penguins", league: "East", division: "Metropolitan", position: "D", height: 72, rings: 0 },
  { name: "Evgeni Malkin", team: "Penguins", league: "East", division: "Metropolitan", position: "C", height: 75, rings: 3 },
  { name: "Kris Letang", team: "Penguins", league: "East", division: "Metropolitan", position: "D", height: 73, rings: 3 },
  { name: "Alex Ovechkin", team: "Capitals", league: "East", division: "Metropolitan", position: "LW", height: 75, rings: 1 },
  { name: "John Carlson", team: "Capitals", league: "East", division: "Metropolitan", position: "D", height: 75, rings: 1 },
  { name: "Tom Wilson", team: "Capitals", league: "East", division: "Metropolitan", position: "RW", height: 76, rings: 1 },
  { name: "Brady Tkachuk", team: "Senators", league: "East", division: "Atlantic", position: "LW", height: 76, rings: 0 },
  { name: "Tim Stützle", team: "Senators", league: "East", division: "Atlantic", position: "C", height: 73, rings: 0 },
  { name: "Claude Giroux", team: "Senators", league: "East", division: "Atlantic", position: "RW", height: 71, rings: 0 },
  { name: "David Krejci", team: "Bruins", league: "East", division: "Atlantic", position: "C", height: 72, rings: 0 },
  { name: "Jeremy Swayman", team: "Bruins", league: "East", division: "Atlantic", position: "G", height: 75, rings: 0 },
  { name: "Linus Ullmark", team: "Senators", league: "East", division: "Atlantic", position: "G", height: 77, rings: 0 },
  { name: "Sebastian Aho", team: "Hurricanes", league: "East", division: "Metropolitan", position: "C", height: 72, rings: 0 },
  { name: "Andrei Svechnikov", team: "Hurricanes", league: "East", division: "Metropolitan", position: "RW", height: 75, rings: 0 },
  { name: "Seth Jarvis", team: "Hurricanes", league: "East", division: "Metropolitan", position: "RW", height: 70, rings: 0 },
  { name: "Jaccob Slavin", team: "Hurricanes", league: "East", division: "Metropolitan", position: "D", height: 75, rings: 0 },
  { name: "Frederik Andersen", team: "Hurricanes", league: "East", division: "Metropolitan", position: "G", height: 76, rings: 0 },
  { name: "Mika Zibanejad", team: "Rangers", league: "East", division: "Metropolitan", position: "C", height: 74, rings: 0 },
  { name: "Adam Fox", team: "Rangers", league: "East", division: "Metropolitan", position: "D", height: 71, rings: 0 },
  { name: "Chris Kreider", team: "Rangers", league: "East", division: "Metropolitan", position: "LW", height: 75, rings: 0 },
  { name: "Vincent Trocheck", team: "Rangers", league: "East", division: "Metropolitan", position: "C", height: 71, rings: 0 },
  { name: "Rasmus Andersson", team: "Flames", league: "West", division: "Pacific", position: "D", height: 73, rings: 0 },
  { name: "Nazem Kadri", team: "Flames", league: "West", division: "Pacific", position: "C", height: 71, rings: 1 },
  { name: "Jonathan Huberdeau", team: "Flames", league: "West", division: "Pacific", position: "LW", height: 73, rings: 0 },
  { name: "Jacob Markstrom", team: "Devils", league: "East", division: "Metropolitan", position: "G", height: 78, rings: 0 },
  { name: "Elias Lindholm", team: "Canucks", league: "West", division: "Pacific", position: "C", height: 73, rings: 0 },
  { name: "Drew Doughty", team: "Kings", league: "West", division: "Pacific", position: "D", height: 73, rings: 2 },
  { name: "Anze Kopitar", team: "Kings", league: "West", division: "Pacific", position: "C", height: 75, rings: 2 },
  { name: "Adrian Kempe", team: "Kings", league: "West", division: "Pacific", position: "LW", height: 74, rings: 0 },
  { name: "Quinton Byfield", team: "Kings", league: "West", division: "Pacific", position: "C", height: 77, rings: 0 },
  { name: "Juuse Saros", team: "Predators", league: "West", division: "Central", position: "G", height: 71, rings: 0 },
  { name: "Filip Forsberg", team: "Predators", league: "West", division: "Central", position: "LW", height: 73, rings: 0 },
  { name: "Ryan O'Reilly", team: "Predators", league: "West", division: "Central", position: "C", height: 72, rings: 1 },
  { name: "Connor Bedard", team: "Blackhawks", league: "West", division: "Central", position: "C", height: 70, rings: 0 },
  { name: "Patrick Kane", team: "Red Wings", league: "East", division: "Atlantic", position: "RW", height: 70, rings: 3 },
  { name: "Alex DeBrincat", team: "Red Wings", league: "East", division: "Atlantic", position: "RW", height: 67, rings: 0 },
  { name: "Dylan Larkin", team: "Red Wings", league: "East", division: "Atlantic", position: "C", height: 73, rings: 0 },
  { name: "Moritz Seider", team: "Red Wings", league: "East", division: "Atlantic", position: "D", height: 76, rings: 0 },
  { name: "Lucas Raymond", team: "Red Wings", league: "East", division: "Atlantic", position: "RW", height: 71, rings: 0 },
  { name: "Cole Caufield", team: "Canadiens", league: "East", division: "Atlantic", position: "RW", height: 67, rings: 0 },
  { name: "Nick Suzuki", team: "Canadiens", league: "East", division: "Atlantic", position: "C", height: 71, rings: 0 },
  { name: "Juraj Slafkovsky", team: "Canadiens", league: "East", division: "Atlantic", position: "LW", height: 76, rings: 0 },
  { name: "Carey Price", team: "Canadiens", league: "East", division: "Atlantic", position: "G", height: 75, rings: 0 },
  { name: "Charlie McAvoy", team: "Bruins", league: "East", division: "Atlantic", position: "D", height: 73, rings: 0 },
  { name: "Brock Boeser", team: "Canucks", league: "West", division: "Pacific", position: "RW", height: 73, rings: 0 },
  { name: "Zach Hyman", team: "Oilers", league: "West", division: "Pacific", position: "LW", height: 73, rings: 0 },
  { name: "Evan Bouchard", team: "Oilers", league: "West", division: "Pacific", position: "D", height: 75, rings: 0 },
  { name: "Ryan Nugent-Hopkins", team: "Oilers", league: "West", division: "Pacific", position: "C", height: 72, rings: 0 },
  { name: "Kailer Yamamoto", team: "Kraken", league: "West", division: "Pacific", position: "RW", height: 68, rings: 0 },
  { name: "Mathew Barzal", team: "Islanders", league: "East", division: "Metropolitan", position: "C", height: 73, rings: 0 },
  { name: "Ilya Sorokin", team: "Islanders", league: "East", division: "Metropolitan", position: "G", height: 75, rings: 0 },
  { name: "Bo Horvat", team: "Islanders", league: "East", division: "Metropolitan", position: "C", height: 72, rings: 0 },
  { name: "Noah Dobson", team: "Islanders", league: "East", division: "Metropolitan", position: "D", height: 76, rings: 0 },
  { name: "Travis Konecny", team: "Flyers", league: "East", division: "Metropolitan", position: "RW", height: 70, rings: 0 },
  { name: "Carter Hart", team: "Flyers", league: "East", division: "Metropolitan", position: "G", height: 74, rings: 0 },
  { name: "Claude Lemieux", team: "Avalanche", league: "West", division: "Central", position: "LW", height: 72, rings: 4 },
];

