// ESPN MLB Rank 2026 Top 100 - 2026 season rosters
const PLAYER_DATA = [
  { name: "Shohei Ohtani", team: "Dodgers", league: "NL", division: "West", position: "DH", age: 31, number: 17, statsType: "hitter", battingAvg: ".283", homeRuns: 55, rbi: 132 },
  { name: "Aaron Judge", team: "Yankees", league: "AL", division: "East", position: "OF", age: 34, number: 99, statsType: "hitter", battingAvg: ".311", homeRuns: 58, rbi: 145 },
  { name: "Bobby Witt Jr.", team: "Royals", league: "AL", division: "Central", position: "SS", age: 26, number: 7, statsType: "hitter", battingAvg: ".311", homeRuns: 30, rbi: 96 },
  { name: "Tarik Skubal", team: "Tigers", league: "AL", division: "Central", position: "P", age: 29, number: 29, statsType: "pitcher", era: "2.97", strikeouts: 204 },
  { name: "Juan Soto", team: "Mets", league: "NL", division: "East", position: "OF", age: 27, number: 22, statsType: "hitter", battingAvg: ".263", homeRuns: 43, rbi: 105 },
  { name: "Paul Skenes", team: "Pirates", league: "NL", division: "Central", position: "P", age: 24, number: 30, statsType: "pitcher", era: "1.96", strikeouts: 251 },
  { name: "Cal Raleigh", team: "Mariners", league: "AL", division: "West", position: "C", age: 29, number: 29, statsType: "hitter", battingAvg: ".250", homeRuns: 60, rbi: 125 },
  { name: "Garrett Crochet", team: "Red Sox", league: "AL", division: "East", position: "P", age: 27, number: 45, statsType: "pitcher", era: "2.76", strikeouts: 255 },
  { name: "Julio Rodriguez", team: "Mariners", league: "AL", division: "West", position: "OF", age: 25, number: 44, statsType: "hitter", battingAvg: ".290", homeRuns: 35, rbi: 98 },
  { name: "Ronald Acuña Jr.", team: "Braves", league: "NL", division: "East", position: "OF", age: 28, number: 13, statsType: "hitter", battingAvg: ".337", homeRuns: 41, rbi: 106 },
  { name: "Vladimir Guerrero Jr.", team: "Blue Jays", league: "AL", division: "East", position: "1B", age: 27, number: 27, statsType: "hitter", battingAvg: ".292", homeRuns: 23, rbi: 84 },
  { name: "José Ramírez", team: "Guardians", league: "AL", division: "Central", position: "3B", age: 33, number: 11, statsType: "hitter", battingAvg: ".284", homeRuns: 32, rbi: 91 },
  { name: "Gunnar Henderson", team: "Orioles", league: "AL", division: "East", position: "SS", age: 24, number: 2, statsType: "hitter", battingAvg: ".268", homeRuns: 28, rbi: 82 },
  { name: "Fernando Tatis Jr.", team: "Padres", league: "NL", division: "West", position: "OF", age: 27, number: 23, statsType: "hitter", battingAvg: ".257", homeRuns: 29, rbi: 95 },
  { name: "Kyle Tucker", team: "Dodgers", league: "NL", division: "West", position: "OF", age: 28, number: 30, statsType: "hitter", battingAvg: ".295", homeRuns: 35, rbi: 109 },
  { name: "Francisco Lindor", team: "Mets", league: "NL", division: "East", position: "SS", age: 32, number: 12, statsType: "hitter", battingAvg: ".258", homeRuns: 28, rbi: 92 },
  { name: "Yoshinobu Yamamoto", team: "Dodgers", league: "NL", division: "West", position: "P", age: 27, number: 18, statsType: "pitcher", era: "2.49", strikeouts: 198 },
  { name: "Corbin Carroll", team: "Diamondbacks", league: "NL", division: "West", position: "OF", age: 25, number: 7, statsType: "hitter", battingAvg: ".282", homeRuns: 27, rbi: 82 },
  { name: "Cristopher Sanchez", team: "Phillies", league: "NL", division: "East", position: "P", age: 28, number: 61, statsType: "pitcher", era: "2.86", strikeouts: 205 },
  { name: "Ketel Marte", team: "Diamondbacks", league: "NL", division: "West", position: "2B", age: 32, number: 4, statsType: "hitter", battingAvg: ".285", homeRuns: 28, rbi: 88 },
  { name: "Kyle Schwarber", team: "Phillies", league: "NL", division: "East", position: "DH", age: 32, number: 12, statsType: "hitter", battingAvg: ".244", homeRuns: 56, rbi: 132 },
  { name: "Pete Crow-Armstrong", team: "Cubs", league: "NL", division: "Central", position: "OF", age: 23, number: 7, statsType: "hitter", battingAvg: ".260", homeRuns: 36, rbi: 85 },
  { name: "Junior Caminero", team: "Rays", league: "AL", division: "East", position: "3B", age: 22, number: 1, statsType: "hitter", battingAvg: ".285", homeRuns: 45, rbi: 112 },
  { name: "Elly De La Cruz", team: "Reds", league: "NL", division: "Central", position: "SS", age: 24, number: 44, statsType: "hitter", battingAvg: ".257", homeRuns: 32, rbi: 94 },
  { name: "Mookie Betts", team: "Dodgers", league: "NL", division: "West", position: "SS", age: 33, number: 50, statsType: "hitter", battingAvg: ".258", homeRuns: 20, rbi: 82 },
  { name: "Trea Turner", team: "Phillies", league: "NL", division: "East", position: "SS", age: 33, number: 7, statsType: "hitter", battingAvg: ".302", homeRuns: 18, rbi: 68 },
  { name: "Logan Webb", team: "Giants", league: "NL", division: "West", position: "P", age: 29, number: 62, statsType: "pitcher", era: "3.25", strikeouts: 210 },
  { name: "William Contreras", team: "Brewers", league: "NL", division: "Central", position: "C", age: 28, number: 24, statsType: "hitter", battingAvg: ".289", homeRuns: 23, rbi: 92 },
  { name: "Nick Kurtz", team: "Athletics", league: "AL", division: "West", position: "1B", age: 23, number: 30, statsType: "hitter", battingAvg: ".305", homeRuns: 45, rbi: 110 },
  { name: "Pete Alonso", team: "Orioles", league: "AL", division: "East", position: "1B", age: 31, number: 20, statsType: "hitter", battingAvg: ".272", homeRuns: 38, rbi: 126 },
  { name: "Hunter Brown", team: "Astros", league: "AL", division: "West", position: "P", age: 27, number: 58, statsType: "pitcher", era: "2.64", strikeouts: 377 },
  { name: "Geraldo Perdomo", team: "Diamondbacks", league: "NL", division: "West", position: "SS", age: 26, number: 2, statsType: "hitter", battingAvg: ".268", homeRuns: 22, rbi: 85 },
  { name: "Roman Anthony", team: "Red Sox", league: "AL", division: "East", position: "OF", age: 21, number: 18, statsType: "hitter", battingAvg: ".286", homeRuns: 31, rbi: 84 },
  { name: "Will Smith", team: "Dodgers", league: "NL", division: "West", position: "C", age: 30, number: 16, statsType: "hitter", battingAvg: ".296", homeRuns: 24, rbi: 82 },
  { name: "Max Fried", team: "Yankees", league: "AL", division: "East", position: "P", age: 32, number: 54, statsType: "pitcher", era: "2.86", strikeouts: 185 },
  { name: "Freddie Freeman", team: "Dodgers", league: "NL", division: "West", position: "1B", age: 36, number: 5, statsType: "hitter", battingAvg: ".295", homeRuns: 25, rbi: 102 },
  { name: "Yordan Alvarez", team: "Astros", league: "AL", division: "West", position: "DH", age: 28, number: 44, statsType: "hitter", battingAvg: ".293", homeRuns: 31, rbi: 97 },
  { name: "Bo Bichette", team: "Mets", league: "NL", division: "East", position: "3B", age: 28, number: 11, statsType: "hitter", battingAvg: ".304", homeRuns: 22, rbi: 88 },
  { name: "Wyatt Langford", team: "Rangers", league: "AL", division: "West", position: "OF", age: 24, number: 19, statsType: "hitter", battingAvg: ".265", homeRuns: 25, rbi: 78 },
  { name: "Matt Olson", team: "Braves", league: "NL", division: "East", position: "1B", age: 32, number: 28, statsType: "hitter", battingAvg: ".270", homeRuns: 38, rbi: 108 },
  { name: "Corey Seager", team: "Rangers", league: "AL", division: "West", position: "SS", age: 32, number: 5, statsType: "hitter", battingAvg: ".265", homeRuns: 28, rbi: 85 },
  { name: "Bryce Harper", team: "Phillies", league: "NL", division: "East", position: "1B", age: 33, number: 3, statsType: "hitter", battingAvg: ".284", homeRuns: 39, rbi: 111 },
  { name: "Jackson Merrill", team: "Padres", league: "NL", division: "West", position: "OF", age: 23, number: 3, statsType: "hitter", battingAvg: ".274", homeRuns: 22, rbi: 75 },
  { name: "James Wood", team: "Nationals", league: "NL", division: "East", position: "OF", age: 23, number: 30, statsType: "hitter", battingAvg: ".285", homeRuns: 41, rbi: 95 },
  { name: "Jackson Chourio", team: "Brewers", league: "NL", division: "Central", position: "OF", age: 22, number: 11, statsType: "hitter", battingAvg: ".268", homeRuns: 21, rbi: 72 },
  { name: "Bryan Woo", team: "Mariners", league: "AL", division: "West", position: "P", age: 26, number: 39, statsType: "pitcher", era: "2.94", strikeouts: 165 },
  { name: "Manny Machado", team: "Padres", league: "NL", division: "West", position: "3B", age: 33, number: 13, statsType: "hitter", battingAvg: ".270", homeRuns: 30, rbi: 98 },
  { name: "Jeremy Peña", team: "Astros", league: "AL", division: "West", position: "SS", age: 28, number: 3, statsType: "hitter", battingAvg: ".304", homeRuns: 22, rbi: 88 },
  { name: "Riley Greene", team: "Tigers", league: "AL", division: "Central", position: "OF", age: 25, number: 31, statsType: "hitter", battingAvg: ".268", homeRuns: 36, rbi: 95 },
  { name: "Hunter Greene", team: "Reds", league: "NL", division: "Central", position: "P", age: 26, number: 21, statsType: "pitcher", era: "3.00", strikeouts: 202 },
  { name: "Chris Sale", team: "Braves", league: "NL", division: "East", position: "P", age: 37, number: 41, statsType: "pitcher", era: "2.58", strikeouts: 195 },
  { name: "Cody Bellinger", team: "Yankees", league: "AL", division: "East", position: "OF", age: 29, number: 35, statsType: "hitter", battingAvg: ".288", homeRuns: 30, rbi: 98 },
  { name: "Zach Neto", team: "Angels", league: "AL", division: "West", position: "SS", age: 25, number: 9, statsType: "hitter", battingAvg: ".262", homeRuns: 22, rbi: 72 },
  { name: "Alejandro Kirk", team: "Blue Jays", league: "AL", division: "East", position: "C", age: 27, number: 30, statsType: "hitter", battingAvg: ".285", homeRuns: 18, rbi: 68 },
  { name: "Nico Hoerner", team: "Cubs", league: "NL", division: "Central", position: "2B", age: 28, number: 2, statsType: "hitter", battingAvg: ".283", homeRuns: 15, rbi: 65 },
  { name: "Rafael Devers", team: "Giants", league: "NL", division: "West", position: "DH", age: 29, number: 11, statsType: "hitter", battingAvg: ".272", homeRuns: 28, rbi: 102 },
  { name: "Logan Gilbert", team: "Mariners", league: "AL", division: "West", position: "P", age: 29, number: 36, statsType: "pitcher", era: "3.25", strikeouts: 195 },
  { name: "Matt Chapman", team: "Giants", league: "NL", division: "West", position: "3B", age: 32, number: 26, statsType: "hitter", battingAvg: ".268", homeRuns: 24, rbi: 78 },
  { name: "Dylan Cease", team: "Blue Jays", league: "AL", division: "East", position: "P", age: 30, number: 84, statsType: "pitcher", era: "4.55", strikeouts: 220 },
  { name: "Mason Miller", team: "Padres", league: "NL", division: "West", position: "P", age: 27, number: 48, statsType: "pitcher", era: "1.89", strikeouts: 85 },
  { name: "Alex Bregman", team: "Cubs", league: "NL", division: "Central", position: "3B", age: 31, number: 2, statsType: "hitter", battingAvg: ".268", homeRuns: 25, rbi: 88 },
  { name: "Willy Adames", team: "Giants", league: "NL", division: "West", position: "SS", age: 29, number: 27, statsType: "hitter", battingAvg: ".225", homeRuns: 32, rbi: 82 },
  { name: "Byron Buxton", team: "Twins", league: "AL", division: "Central", position: "OF", age: 32, number: 25, statsType: "hitter", battingAvg: ".262", homeRuns: 35, rbi: 88 },
  { name: "Jacob deGrom", team: "Rangers", league: "AL", division: "West", position: "P", age: 38, number: 48, statsType: "pitcher", era: "2.97", strikeouts: 175 },
  { name: "Framber Valdez", team: "Tigers", league: "AL", division: "Central", position: "P", age: 32, number: 59, statsType: "pitcher", era: "3.00", strikeouts: 185 },
  { name: "Brent Rooker", team: "Athletics", league: "AL", division: "West", position: "DH", age: 30, number: 25, statsType: "hitter", battingAvg: ".268", homeRuns: 35, rbi: 95 },
  { name: "Jarren Duran", team: "Red Sox", league: "AL", division: "East", position: "OF", age: 29, number: 16, statsType: "hitter", battingAvg: ".271", homeRuns: 22, rbi: 79 },
  { name: "Freddy Peralta", team: "Mets", league: "NL", division: "East", position: "P", age: 30, number: 51, statsType: "pitcher", era: "3.52", strikeouts: 195 },
  { name: "Cole Ragans", team: "Royals", league: "AL", division: "Central", position: "P", age: 28, number: 48, statsType: "pitcher", era: "2.85", strikeouts: 210 },
  { name: "Blake Snell", team: "Dodgers", league: "NL", division: "West", position: "P", age: 33, number: 4, statsType: "pitcher", era: "2.85", strikeouts: 198 },
  { name: "Maikel Garcia", team: "Royals", league: "AL", division: "Central", position: "3B", age: 26, number: 3, statsType: "hitter", battingAvg: ".278", homeRuns: 18, rbi: 82 },
  { name: "Drake Baldwin", team: "Braves", league: "NL", division: "East", position: "C", age: 24, number: 33, statsType: "hitter", battingAvg: ".274", homeRuns: 19, rbi: 78 },
  { name: "Edwin Diaz", team: "Dodgers", league: "NL", division: "West", position: "P", age: 31, number: 39, statsType: "pitcher", era: "2.25", strikeouts: 95 },
  { name: "Brice Turang", team: "Brewers", league: "NL", division: "Central", position: "2B", age: 26, number: 0, statsType: "hitter", battingAvg: ".268", homeRuns: 18, rbi: 72 },
  { name: "Shea Langeliers", team: "Athletics", league: "AL", division: "West", position: "C", age: 27, number: 23, statsType: "hitter", battingAvg: ".275", homeRuns: 28, rbi: 82 },
  { name: "George Kirby", team: "Mariners", league: "AL", division: "West", position: "P", age: 27, number: 68, statsType: "pitcher", era: "4.21", strikeouts: 175 },
  { name: "Joe Ryan", team: "Twins", league: "AL", division: "Central", position: "P", age: 29, number: 41, statsType: "pitcher", era: "3.50", strikeouts: 185 },
  { name: "Jazz Chisholm Jr.", team: "Yankees", league: "AL", division: "East", position: "2B", age: 27, number: 2, statsType: "hitter", battingAvg: ".268", homeRuns: 28, rbi: 82 },
  { name: "Adley Rutschman", team: "Orioles", league: "AL", division: "East", position: "C", age: 27, number: 35, statsType: "hitter", battingAvg: ".255", homeRuns: 22, rbi: 78 },
  { name: "George Springer", team: "Blue Jays", league: "AL", division: "East", position: "OF", age: 36, number: 4, statsType: "hitter", battingAvg: ".295", homeRuns: 32, rbi: 88 },
  { name: "Steven Kwan", team: "Guardians", league: "AL", division: "Central", position: "OF", age: 28, number: 38, statsType: "hitter", battingAvg: ".288", homeRuns: 12, rbi: 58 },
  { name: "Dansby Swanson", team: "Cubs", league: "NL", division: "Central", position: "SS", age: 31, number: 7, statsType: "hitter", battingAvg: ".243", homeRuns: 21, rbi: 74 },
  { name: "Michael Harris II", team: "Braves", league: "NL", division: "East", position: "OF", age: 24, number: 23, statsType: "hitter", battingAvg: ".268", homeRuns: 22, rbi: 72 },
  { name: "Austin Riley", team: "Braves", league: "NL", division: "East", position: "3B", age: 28, number: 27, statsType: "hitter", battingAvg: ".265", homeRuns: 28, rbi: 88 },
  { name: "Ranger Suarez", team: "Red Sox", league: "AL", division: "East", position: "P", age: 30, number: 55, statsType: "pitcher", era: "3.22", strikeouts: 165 },
  { name: "Michael Busch", team: "Cubs", league: "NL", division: "Central", position: "1B", age: 28, number: 13, statsType: "hitter", battingAvg: ".268", homeRuns: 34, rbi: 95 },
  { name: "Jesus Luzardo", team: "Phillies", league: "NL", division: "East", position: "P", age: 28, number: 44, statsType: "pitcher", era: "3.92", strikeouts: 216 },
  { name: "Ceddanne Rafaela", team: "Red Sox", league: "AL", division: "East", position: "OF", age: 25, number: 43, statsType: "hitter", battingAvg: ".265", homeRuns: 22, rbi: 78 },
  { name: "Andrew Abbott", team: "Reds", league: "NL", division: "Central", position: "P", age: 27, number: 28, statsType: "pitcher", era: "3.35", strikeouts: 175 },
  { name: "Jhoan Duran", team: "Phillies", league: "NL", division: "East", position: "P", age: 28, number: 59, statsType: "pitcher", era: "2.06", strikeouts: 92 },
  { name: "Zack Wheeler", team: "Phillies", league: "NL", division: "East", position: "P", age: 36, number: 45, statsType: "pitcher", era: "2.91", strikeouts: 210 },
  { name: "Seiya Suzuki", team: "Cubs", league: "NL", division: "Central", position: "OF", age: 31, number: 27, statsType: "hitter", battingAvg: ".262", homeRuns: 32, rbi: 103 },
  { name: "Aroldis Chapman", team: "Red Sox", league: "AL", division: "East", position: "P", age: 38, number: 54, statsType: "pitcher", era: "1.15", strikeouts: 78 },
  { name: "Jacob Wilson", team: "Athletics", league: "AL", division: "West", position: "SS", age: 24, number: 1, statsType: "hitter", battingAvg: ".311", homeRuns: 12, rbi: 68 },
  { name: "Kevin Gausman", team: "Blue Jays", league: "AL", division: "East", position: "P", age: 35, number: 34, statsType: "pitcher", era: "3.34", strikeouts: 195 },
  { name: "Eugenio Suarez", team: "Reds", league: "NL", division: "Central", position: "3B", age: 34, number: 7, statsType: "hitter", battingAvg: ".248", homeRuns: 49, rbi: 115 },
  { name: "Josh Naylor", team: "Mariners", league: "AL", division: "West", position: "1B", age: 28, number: 22, statsType: "hitter", battingAvg: ".295", homeRuns: 25, rbi: 98 },
  { name: "CJ Abrams", team: "Nationals", league: "NL", division: "East", position: "SS", age: 25, number: 5, statsType: "hitter", battingAvg: ".268", homeRuns: 24, rbi: 75 },
  { name: "Nathan Eovaldi", team: "Rangers", league: "AL", division: "West", position: "P", age: 36, number: 17, statsType: "pitcher", era: "1.73", strikeouts: 175 },
  { name: "Nolan McLean", team: "Mets", league: "NL", division: "East", position: "P", age: 23, number: 28, statsType: "pitcher", era: "3.13", strikeouts: 176 },
];
